In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
stock= yf.download(
    "RELIANCE.NS",
    start="2014-01-01",
    end="2024-12-31"
)

[*********************100%***********************]  1 of 1 completed

In [4]:
stock.head()

Price            Close        High         Low        Open      Volume
Ticker     RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS
Date
2014-01-01  187.467300  189.460511  187.214187  189.291764     5849398
2014-01-02  184.556564  188.985922  183.523049  187.235265     6023632
2014-01-03  182.289139  184.208529  180.338112  183.839412    12833897
2014-01-06  180.327591  182.078248  179.283530  181.835681    13315857
2014-01-07  177.617249  181.382194  177.184857  180.253766    17311470

In [5]:
stock.shape

(2710, 5)

In [6]:
stock.columns

MultiIndex([( 'Close', 'RELIANCE.NS'),
            (  'High', 'RELIANCE.NS'),
            (   'Low', 'RELIANCE.NS'),
            (  'Open', 'RELIANCE.NS'),
            ('Volume', 'RELIANCE.NS')],
           names=['Price', 'Ticker'])

In [7]:
stock.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2710 entries, 2014-01-01 to 2024-12-30
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Close, RELIANCE.NS)   2710 non-null   float64
 1   (High, RELIANCE.NS)    2710 non-null   float64
 2   (Low, RELIANCE.NS)     2710 non-null   float64
 3   (Open, RELIANCE.NS)    2710 non-null   float64
 4   (Volume, RELIANCE.NS)  2710 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 127.0 KB

In [8]:
stock.describe()

Price         Close         High          Low         Open        Volume
Ticker  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS   RELIANCE.NS
count   2710.000000  2710.000000  2710.000000  2710.000000  2.710000e+03
mean     679.920916   687.369975   673.087924   680.420016  1.807056e+07
std      425.998872   430.038778   422.277033   426.303229  1.313834e+07
min      168.726883   170.171747   167.282068   168.758569  0.000000e+00
25%      228.287460   230.684011   225.898603   228.412863  1.060173e+07
50%      566.907776   573.598713   561.678065   567.881518  1.448569e+07
75%     1095.455505  1106.019810  1084.534487  1097.720016  2.059643e+07
max     1581.824463  1589.630354  1566.607971  1585.332124  1.426834e+08

In [9]:
stock.to_csv("../data/reliance_stock_data.csv")