In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
stock=pd.read_csv("../data/reliance_features_v1.csv", index_col=0,parse_dates=True)
stock.head()

,Close,High,Low,Open,Volume,Return,MA_5,MA_20,Volatility_20
Date,,,,,,,,,
2014-01-01,187.467316,189.460526,187.214203,189.291780,5849398,NaN,NaN,NaN,NaN
2014-01-02,184.556564,188.985922,183.523049,187.235265,6023632,-0.015527,NaN,NaN,NaN
2014-01-03,182.289169,184.208559,180.338142,183.839443,12833897,-0.012286,NaN,NaN,NaN
2014-01-06,180.327576,182.078233,179.283514,181.835666,13315857,-0.010761,NaN,NaN,NaN
2014-01-07,177.617279,181.382225,177.184888,180.253797,17311470,-0.015030,182.451581,NaN,NaN

In [3]:
stock['Tomorrow_Close']=stock['Close'].shift(-1)

In [4]:
stock['Target']=np.where(stock['Tomorrow_Close'] > stock['Close'], 1, 0)

In [5]:
stock[['Close', 'Tomorrow_Close', 'Target']].head(10)

                 Close  Tomorrow_Close  Target
Date
2014-01-01  187.467316      184.556564       0
2014-01-02  184.556564      182.289169       0
2014-01-03  182.289169      180.327576       0
2014-01-06  180.327576      177.617279       0
2014-01-07  177.617279      179.083176       1
2014-01-08  179.083176      179.431168       1
2014-01-09  179.431168      181.002563       1
2014-01-10  181.002563      185.695557       1
2014-01-13  185.695557      185.927567       1
2014-01-14  185.927567      186.760696       1

In [6]:
stock['Lag_1'] = stock['Return'].shift(1)

In [7]:
stock['Lag_2'] = stock['Return'].shift(2)

In [8]:
stock['Lag_3'] = stock['Return'].shift(3)

In [9]:
stock[['Return', 'Lag_1', 'Lag_2', 'Lag_3']].head(10)

              Return     Lag_1     Lag_2     Lag_3
Date
2014-01-01       NaN       NaN       NaN       NaN
2014-01-02 -0.015527       NaN       NaN       NaN
2014-01-03 -0.012286 -0.015527       NaN       NaN
2014-01-06 -0.010761 -0.012286 -0.015527       NaN
2014-01-07 -0.015030 -0.010761 -0.012286 -0.015527
2014-01-08  0.008253 -0.015030 -0.010761 -0.012286
2014-01-09  0.001943  0.008253 -0.015030 -0.010761
2014-01-10  0.008758  0.001943  0.008253 -0.015030
2014-01-13  0.025928  0.008758  0.001943  0.008253
2014-01-14  0.001249  0.025928  0.008758  0.001943

In [10]:
stock.isnull().sum()

Close              0
High               0
Low                0
Open               0
Volume             0
Return             1
MA_5               4
MA_20             19
Volatility_20     20
Tomorrow_Close     1
Target             0
Lag_1              2
Lag_2              3
Lag_3              4
dtype: int64

In [11]:
stock.dropna(inplace=True)

In [13]:
stock.isnull().sum()

Close             0
High              0
Low               0
Open              0
Volume            0
Return            0
MA_5              0
MA_20             0
Volatility_20     0
Tomorrow_Close    0
Target            0
Lag_1             0
Lag_2             0
Lag_3             0
dtype: int64

In [14]:
stock.to_csv("../data/reliance_m1_dataset.csv")